datasrc.username=blrs_app
datasrc.password=blrs@123
datasrc.url=jdbc:postgresql://192.168.2.17:5432/blrs

spring.datasource.url=jdbc:postgresql://192.168.2.17:5432/blrs
spring.datasource.username=blrs_app
spring.datasource.password=blrs@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect

# Default App Values
default.password=Bornfire@123
default.pagesize=500

# File Output Path
output.exportpath=D:\\
document.folder.path=C:/path/to/your/document/folder


# HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.leak-detection-threshold=30000

# Session
spring.session.store-type=jdbc
spring.session.timeout=60000s
server.servlet.session.timeout=60000s


# Fixes common Oracle LOB issues
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
spring.jpa.properties.hibernate.jdbc.batch_size=0
# Forces Hibernate to not wrap LOBs in a way that requires an active connection for too long
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Hibernate
# Remove or comment out: spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Use this instead to force Hibernate's hand:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# IMPORTANT - prevent table recreation/update
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false

# Server
server.servlet.context-path=/BLRS
server.port=8090

# Security
spring.resources.add-mappings=true

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB